# Generated by Django 5.0.6 on 2024-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0002_userdata_created_at_userdata_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
