FROM ubuntu:22.04
ENV PYTHONUNBUFFERED=1
RUN apt update && apt upgrade -y
RUN apt install -y python3-dev python3-pip build-essential libpq-dev
RUN pip3 install pipenv tzdata psycopg2
COPY ./backend/ /home/
WORKDIR /home/
RUN pipenv install --system
EXPOSE 8000

# ENTRYPOINT MUST BE CHANGED LATER IN PROD, AS DB WILL ALREADY HAVE TABLES
ENTRYPOINT ["sh","-c","if [ ! -z \"$RUN_MIGRATION\" ]; then python3 manage.py makemigrations myapi; python3 manage.py migrate; fi && python3 manage.py runserver 0.0.0.0:8000"]
