FROM node:lts-alpine
COPY ./frontend/ /home/
WORKDIR /home/
RUN npm install
RUN npm run build


FROM nginx:stable-alpine
COPY --from=0 /home/dist /home
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]
