FROM ubuntu:22.04
RUN apt update && apt upgrade
RUN apt install -y python3 python3-pip && pip3 install pipenv tzdata
ENV PYTHONUNBUFFERED=1
COPY ./backend/ /home/
WORKDIR /home/
RUN pipenv install --system
EXPOSE 8000
ENTRYPOINT ["python3","manage.py","runserver","0.0.0.0:8000"]
